services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        
    Paladin\UserBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']
        
    Paladin\UserBundle\Command\CreateUserCommand:
        tags:
            - { name: 'console.command', command: 'paladin:user:create' }